### PR TITLE
/def/geochem

### PR DESCRIPTION
**Pull request by nicholascar**

### CODE REVIEW

**Comment by rwalkerands** [comment]
GitHub offered to rebase the most recent merge commit in master back into staging; I accepted the offer. This (correctly) forced a re-test of staging.

**Review by rwalkerands — APPROVED** [review]

**Comment by rwalkerands** [comment]
Hmm, not sure GitHub's offer was a good one. staging now says "This branch is [2 commits ahead](https://github.com/AGLDWG/pid-proxy/compare/master...staging), [2 commits behind](https://github.com/AGLDWG/pid-proxy/compare/staging...master) master."

So, even though the content is merged, we may see the two commits of this PR appear again for the next PR into master.

**Comment by rwalkerands** [comment]
Deployed.

**Comment by nicholascar** [comment]
Thanks. Can't say I really understand but I'm sure I will after the next 50+ updates I make...

**Pull request merged**
