### PR TITLE
CSIRO Causal Networks redirections and tests

### PR DESCRIPTION
**Pull request by ashleysommer**
See AGLDWG Dataset https://catalogue.linked.data.gov.au/resource/337
and AGLDWG Ontology https://catalogue.linked.data.gov.au/resource/338

### CODE REVIEW

**Comment by rwalkerands** [comment]
Hey @ashleysommer, our process requires PRs be into `staging`; I rebased for you. I will send you a link to the draft doc of our process via email.

**Comment by ashleysommer** [comment]
Hi @rwalkerands 
 Now that you mention it, I do remember reading somewhere the PR should be done against `staging`, it must've slipped my mind when writing these ones.
Thanks for rebasing.

**Comment by rwalkerands** [comment]
Over to Nick (and possibly also one or more trainee reviewers).

**Comment by rwalkerands** [comment]
(Hmm/tip: Registry Status = "Submitted".)

**Comment by ashleysommer** [comment]
FYI, the target server is now up and running with proper content negotiation and support for turtle, rdf/xml, and json-ld for the ontology and the dataset identifiers.

**Comment by nicholascar** [comment]
@ashleysommer doing the review early next week and will push it through then. Will be in production a day or two after that, so by about Thursday.

**Comment by ashleysommer** [comment]
Thanks for the update Nick

**Comment by ardc-developers** [comment]
See PR #111 for the continuation.

**Pull request merged**
