### PR TITLE
Continue #68: Tern new dataset and update endpoints

### PR DESCRIPTION
**Pull request by rwalkerands**
Continuation of #68 .

For Nick to review.

### CODE REVIEW

**Comment by rwalkerands** [comment]
@javiersan18 : the test suite failed; test cases don't match the changes to the rewrites.

Please see test output at https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/LST-RAVS14-JOB1-2.txt

Tip: scroll to the end.

**Comment by javiersan18** [comment]
> @javiersan18 : the test suite failed; test cases don't match the changes to the rewrites.
> 
> Please see test output at https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/LST-RAVS14-JOB1-2.txt
> 
> Tip: scroll to the end.

Hi Richard, thanks for your help.

I am confused about the test workflow here. Are the tests executed against the current staging branch? or executed against my branch?

It seems to me like the tests are executed against the current staging branch, so the changes requested in the PR are not yet applied:

For file 'linked.data.gov.au/org/tern.json', test 'AusPlots Dataset Metadata HTML', URI https://linked.data.gov.au/dataset/ausplots did not redirect to https://linkeddata.tern.org.au/viewers/general?uri=http://linked.data.gov.au/dataset/ausplots&sparql_endpoint=**https://virtuoso.tern.org.au/sparql** as expected, instead https://linkeddata.tern.org.au/viewers/general?uri=http://linked.data.gov.au/dataset/ausplots&sparql_endpoint=**https://graphdb.tern.org.au/repositories/ecoplots**

where graphDB is before the changes.

Thanks again for your help.
Cheers

**Comment by rwalkerands** [comment]
Sorry that we don't yet have the ability to run the suite directly against your PRs, but we have to merge them here first. I'll see what I can do about that.

In the mean time:

I've confirmed that the test suite has run against all your changes, and the output is correct.

If you look at the rewrites as they are in your local fork/branch:

https://github.com/ternaustralia/pid-proxy/blob/tern/new_dataset_and_update_endpoints/conf/linked.data.gov.au/org/tern.conf

you'll see that you missed some places when you did a search/replace.

E.g., lines 30-31:

```
# HTML
RewriteRule ^/dataset/ausplots(.*)$ https://linkeddata.tern.org.au/viewers/general?uri=http://linked.data.gov.au/dataset/ausplots$1&sparql_endpoint=https://graphdb.tern.org.au/repositories/ecoplots [R=302,L]
```

This still refers to GraphDB.

Same goes for the other PIDs.

So please add a fix to your local branch, and (sorry again) make another PR.

**Comment by javiersan18** [comment]
Ohh I am so sorry, I have missed to update some rules... I will update them.

Workflow in this case would be:

1. I fix my local branch : [ternaustralia:tern/new_dataset_and_update_endpoints](https://github.com/ternaustralia/pid-proxy/tree/tern/new_dataset_and_update_endpoints)
2. I create a new PR from my local branch to staging.
3. You merge my local branch to [AGLDWG:tern-new_dataset_and_update_endpoints](https://github.com/AGLDWG/pid-proxy/tree/tern-new_dataset_and_update_endpoints)
4. we continue with this PR review

It his correct? 

Thanks and sorry again.
Cheers

**Comment by javiersan18** [comment]
I have created the following PR:
https://github.com/AGLDWG/pid-proxy/pull/70

Thank you

**Comment by rwalkerands** [comment]
@javiersan18 tests now pass.

Over to Nick.

**Comment by rwalkerands** [comment]
@nicholascar see also comment at #68 :

> Related to the new dataset, I have also applied to the creation of the PID, but I am nor sure about the status of that request:
https://catalogue.linked.data.gov.au/resource/330

**Comment by javiersan18** [comment]
> @javiersan18 tests now pass.
> 
> Over to Nick.

Thank you very much

**Review by nicholascar — APPROVED** [review]

**Comment by rwalkerands** [comment]
Ahem ... @nicholascar see also comment at https://github.com/AGLDWG/pid-proxy/pull/68 :

>     Related to the new dataset, I have also applied to the creation of the PID, but I am nor sure about the status of that request:
>    https://catalogue.linked.data.gov.au/resource/330

This still has status "Submitted". Will you approve?

**Comment by rwalkerands** [comment]
Nick approved the creation of the PID

**Comment by rwalkerands** [comment]
Deployed.

**Comment by javiersan18** [comment]
Thanks for your help.


Javier Sánchez.

________________________________
De: Richard Walker ***@***.***>
Enviado: lunes, 18 de diciembre de 2023 10:50
Para: AGLDWG/pid-proxy ***@***.***>
Cc: Javier Sánchez ***@***.***>; Mention ***@***.***>
Asunto: Re: [AGLDWG/pid-proxy] Continue #68: Tern new dataset and update endpoints (PR #69)


Deployed.

**Pull request merged**
