### PR TITLE
Redirect dev to prod

### PR DESCRIPTION
**Pull request by gswa-hub**
Change the redirect link from Dev to Prod

### CODE REVIEW

**Comment by rwalkerands** [comment]
Acknowledging receipt of this PR.

I've run the test suite on your changes, and it passes.

Sorry, there's currently a hold-up with another PR; once that's sorted, I'll let you know ...

(FYI/heads-up: you'll then need to do a rebase against the upstream staging branch.)

**Comment by nicholascar** [comment]
Merging into local pid-proxy branch to then submit to staging

**Comment by rwalkerands** [comment]
> (FYI/heads-up: you'll then need to do a rebase against the upstream staging branch.)

OK, apparently that didn't happen, but it's OK.

**Comment by rwalkerands** [comment]
Deployed.

**Pull request merged**
