### PR TITLE
Test process do not merge 2

### PR DESCRIPTION
**Pull request by rwalkerands**
Testing of automation support: DO NOT MERGE!

### CODE REVIEW

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by ardc-developers** [comment]
The test suite was run, and failed. Log: https://staging-linkeddata-rewriter-nectar.ardc.edu.au/test-logs/PR104.txt

**Comment by rwalkerands** [comment]
The processes seem to be working OK; closing this.

**Pull request closed without merging**
