### PR TITLE
Adding redirection rules for new Three-Parks-Savanna dataset

### PR DESCRIPTION
**Pull request by javiersan18**
Add redirect for https://linked.data.gov.au/dataset/three-parks-savanna. Thanks!

Best regards,
Javier Sanchez, TERN

### CODE REVIEW

**Comment by rwalkerands** [comment]
We (Nick and I) are currently refining the processes for pull requests. Sorry, we don't yet have a public document explaining it.

So your request is timely.

Your PR is from your repo/branch that's 83 commits behind our master branch. Please rebase your clone of this repo. You may have to fix some conflicts ... Then let's see if GitHub updates this PR to match.

Also, we have a test suite; Nick, please have a look and advise.

In any case, I'll edit the PR to redirect it into a feature branch so that the test suite can do its thing.

**Comment by rwalkerands** [comment]
Rebased this PR into a new branch PR50 cloned from master.

**Comment by rwalkerands** [comment]
This is for https://catalogue.linked.data.gov.au/resource/297 , currently with Registry Status "Submitted".

**Comment by javiersan18** [comment]
Hi Richard,

Thanks for the help and clarification. I have pulled the 83 commits from your master to my repo's master, no conflicts. 
Yes, this redirection is related to the resource indicated. I have also contacted Nick to review my request in the catalogue.

What next step should I do now?

Thank you very much in advance.
Javier

**Comment by rwalkerands** [comment]
Commits merged into our feature branch, and now showing a tick at https://github.com/AGLDWG/pid-proxy/tree/PR50 .

Next step is to add tests to the test suite; Nick to continue the conversation at this point.

When ready, we will do the push to `staging`, then to `master`, then deploy.

**Pull request merged**
